# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-30 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190730_1103'),
        ('crm', '0003_auto_20190729_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='yonghudejiaose'),
        ),
    ]
