# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-30 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='TITLE')),
                ('is_menu', models.BooleanField(default=False, verbose_name='IS_MENU')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='ROLENAME')),
                ('permissions', models.ManyToManyField(blank=True, null=True, to='rbac.Permission', verbose_name='ROLEandPER')),
            ],
        ),
    ]
